### ISSUE TITLE
Copy hangs in endless sleep state

### ISSUE THREAD

**Issue by a1an77** [husio/python-sqlite3-backup#14]
With version 1.3 often copying a 2.6 GB database file to a memory database hangs up indefinitely (interrupted after 16 hours) instead of taking a few minutes to complete.
The problem appears intermittently and I've not been able to pinpoint a specific cause. 
The file lies on an NFS network if that might contribute to the behaviour.
There are no other processes accessing the file at the same time and the memory db is private to the thread.
Using version 1.2.1 works flawlessly

PS: I suspect that for some reason the copy loop gets stuck into an SQLITE_LOCKED issue with itself, ending up sleeping indefinitely

**Comment by husio** [comment]
Thanks for the report. 
This sounds like a regression that is not covered by tests. I will give it a try on the weekend.

**Comment by husio** [comment]
How do you call `copy` function?

**Comment by a1an77** [comment]
I call it in an instance method with 

    sqlitebck.copy(sqliteFile, self.sqlite)

where self.sqlite is an in-memory instance
How can I test using #15 ?

**Comment by husio** [comment]
You have to [pip install pointing directly at this hash](https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip), I believe it will be:

```sh
$ pip install git+git://github.com/husio/python-sqlite3-backup@b7ea6a5d6024d95c55d35f0d806144088f516edb
```
Then run your script as usual.

Let me know if you have any troubles.

**Comment by a1an77** [comment]
Seems to work again now!

**Comment by husio** [comment]
I will merge and release this as 1.4. Please make sure this version works for you as well and then I will close this issue.

**Comment by a1an77** [comment]
Worked good five times in a row so I would confirm
